::Const.CharacterVillageBackgrounds.extend([
	::Legends.Background.Beggar,
	::Legends.Background.Graverobber,
	::Legends.Background.Houndmaster,
	::Legends.Background.Butcher,
	::Legends.Background.Ratcatcher,
	::Legends.Background.Servant,
	::Legends.Background.Mason,
	::Legends.Background.Shepherd,
	::Legends.Background.Brawler,
	::Legends.Background.Thief,
	::Legends.Background.Militia,
	::Legends.Background.Peddler,
	::Legends.Background.Poacher,
	::Legends.Background.Vagabond
]);
