::Const.World.LocationNames.VillageWestern.extend([
	"Lieske",
	"Grenzstadt",
	"Loningbruck",
	"Streissen",
	"Heideck",
	"Carroburg",
	"Delberz",
	"Untergard",
	"Grimmenhagen",
	"Drakenburg",
	"Dietershafen",
	"Norden",
	"Beelen",
	"Gelting",
	"Ockholm",
	"Fortenhaf",
	"Elbing",
	"Durben",
	"Ziesholz",
	"Brunfahre",
	"Heffengen",
	"Hermsdorf",
	"Remer",
	"Reitwein",
	"Gerdouen",
	"Dorna",
	"Burgenhof",
	"Fichetal",
	"Eisental",
	"Weiler",
	"Rheden",
	"Grunackeren",
	"Wendorf",
	"Felde",
	"Limshof",
	"Rossin",
	"Lowitz",
	"Schonfeld",
	"Birkewiese",
	"Bohsenfels",
	"Dassel",
	"Boven",
	"Grenzburg",
	"Vandengart",
	"Lubrecht",
	"Trillheim",
	"Roezfels",
	"Gipfel",
	"Birnbaum",
	"Dietfurt",
	"Hutten",
	"Haukern",
	"Eicheschatten",
	"Grunhugel",
	"Wuppertal",
	"Loningbruck",
	"Merfeld",
	"Hochsleben",
	"Pfungzig",
	"Auerswald",
	"Diesdorf",
	"Dunkelberg",
	"Eilhart",
	"Frederheim",
	"Glukshalt",
	"Glumund",
	"Grunburg",
	"Holthusen",
	"Weissbruck",
	"Wheburg",
	"Worlin",
	"Zhanstadt",
	"Ubersreik",
	"Tallerhof",
	"Stromdorf",
	"Stimmigen",
	"Schadelheim",
	"Schilderheim",
	"Rottfurt",
	"Kemperbad",
	"Maselhof",
	"Roherhausen",
	"Weningen",
	"Halgerbach",
	"Durbheim",
	"Pfieldorf",
	"Elzach",
	"Hinkend",
	"Mauchen",
	"Hausern",
	"Owingen",
	"Meissen",
	"Heisenberg",
	"Kelgard",
	"Nehren",
	"Trulben",
	"Salmfahre",
	"Rohrhof",
	"Geschburg",
	"Althausen",
	"Hurlach",
	"Moasach",
	"Pforzen",
	"Elzach",
	"Bernau",
	"Staig",
	"Ellwangen",
	"Ballenhof",
	"Waldbach",
	"Steingart",
	"Pahl",
	"Eppiswald",
	"Eigenhof",
	"Wusterburg",
	"Kell",
	"Sonnefurt",
	"Halgerbach",
	"Serrig",
	"Weilerburg",
	"Kreutzhofen",
	"Oshaussen",
	"Ummenbach",
	"Mendlehof",
	"Jengen",
	"Osterzell",
	"Krudenwald",
	"Selmigerholz",
	"Holzbeck",
	"Hovelhof",
	"Wahnsinningen",
	"Esk",
	"Ahresdorf",
	"Bergsburg",
	"Koerin",
	"Breder",
	"Bergendorf",
	"Heedendorf",
	"Flaschfurt",
	"Barwedel",
	"Euthorst",
	"Tussenhof",
	"Langweise",
	"Gruyden",
	"Estorf",
	"Stockse",
	"Muden",
	"Vodf",
	"Dunstigfurt",
	"Eichewaldchen",
	"Hexenwald",
	"Wolkensang",
	"Morgenfels",
	"Rune",
	"Feenquelle",
	"Fafner",
	"Falkenhorst"

]);
::Const.World.LocationNames.CityWestern.extend([
	"Altdorf",
	"Averheim",
	"Mordheim",
	"Wolfenberg",
	"Talabheim",
	"Bechafen",
	"Middenheim",
	"Nuln",
	"Essen",
	"Wurtbad",
	"Hergig",
	"Wissenberg",
	"Wallstadt",
	"Beagleburg",
	"Zauberdorf",
	"Zwergenburg",
	"Donnerstadt",
	"Eichenheim",
	"Rabenspitz",
	"Falkenruh",
	"Sagenstein",
	"Zwergenhold",
	"Elfenstadt",
	"Runentor",
	"Wolkendom",
	"Silberfluss",
	"Hexenkreis",
	"Eiswacht",
	"Sturmheim",
	"Götterturm",
	"Drachenhafen",
	"Frieren",
	"Nebelsteg",
	"Himmelstadt",
	"Sonnenwacht",
	"Eichenherz",
	"Geisterstadt",
	"Wolkensee",
	"Feuerberg",
	"Elfenwarte",
	"Frostheim",
	"Rabenstadt",
	"Feuerschmiede",
	"Steinkreuz",
	"Falkenhorde",
	"Sonnensturm",
	"Nebelschloss",
	"Rabenwacht",
	"Felsenheim",
	"Himmelstadt",
	"Sturmfels",
	"Falkenhof",
	"Drachenfurt",
	"Goldbach",
	"Rosenheim",
	"Wolkenruhe",
	"Silberquelle",
	"Nebelgrund",
	"Traumstadt",
	"Feuerstein",
	"Rabenschatten",
	"Goldfels",
	"Teufelswarte",
	"Bachstadt",
	"Lindental",
	"Kristallstadt",
	"Ahornstadt",
	"Klingenstadt",
	"Steinadler",
	"Schatzstadt",
	"Kieselstein",
	"Schmiedetal",
	"Felsgrund",
	"Wolfschlucht",
	"Himmelsruhe"
]);

::Const.World.LocationNames.GuardTower.extend([
	"Blackstone Tower",
	"Keeper\'s Watch",
	"The Stone",
	"Atonement Tower",
	"Black Watch",
	"Dawnguard Lookout",
	"The Watch",
	"Warden\'s Keep",
	"Watchman\'s Eyrie",
	"Watchman\'s Regret",
	"Watchman\'s Haunt",
	"Defender\'s Roost",
	"Night Watch",
	"Rampart Sentinel",
	"Watchful Bastion",
	"Nobby\'s Tower",
	"Shieldmaiden Tower",
	"Justice Pillar",
	"Tithing Tower",
	"The Old Sentry",
	"The Creaking Vigil",
	"Goldcloak Lookout",
	"Silverblood Sentry",
	"Bronze Bell Tower",
	"Firewatch Tower",
	"Greenskin Lookout",
	"Paladin Watch",
	"Burnt Tower",
	"Lavender Tower",
	"Haunted Lookout",
	"Hangman\'s Watch",
	"Grim Lookout",
	"The Old Watchtower"
]);

::Const.World.LocationNames.Castle.extend([
	"Bohsenfels Castle",
	"Castle Kreiglitz",
	"Castle Lenkster",
	"Castle Reikguard",
	"Woodcroft Tower",
	"Middenstag Castle",
	"Helmgart Castle",
	"Heldenhame Keep",
	"Drachenstein Castle",
	"Falkenschild Keep",
	"Nebelstein Keep",
	"Silberfeste Citadel",
	"Wolkenspitz Castle",
	"Rabenfels Keep",
	"Runenherz Bastion",
	"Runenfeste Keep",
	"Eichenwacht Castle",
	"Geisterhalle Keep",
	"Bergkron Citadel",
	"Kristallturm Keep",
	"Wolkenzahn Citadel",
	"Frostklippe Bastion",
	"Castle Mondlicht",
	"Segensstein Keep",
	"Castle Hoffnungs",
	"Sternen Castle",
	"Gotteshof Castle",
	"Himmelshafen Keep",
	"Engelstal Castle",
	"Geistertal Keep",
	"Steinwall Castle",
	"Eisenbach Keep",
	"Steinbrücke Keep",
	"Castle Wolfsfluch",
	"Hexenfluch Citadel",
	"Sturmfaust Bastion",
	"Blut Keep",
	"Rot Keep",
	"Eisenblut Keep",
	"Castle Morgenwache",
	"Goldspire Bastion",
	"Sonnen Castle",
	"Hirschberg Keep",
	"Sturmwacht Keep",
	"Dunkelmoor Castle",
	"Castle Grim",
	"Castle Leichenfeld",
	"Finsterwalde Keep",
	"Amber Bastion",
	"Seelengrab Citadel",
	"Fluchbrücke Keep",
	"Blutgrube Bastion",
	"Castle Grabfeld",
	"Kristallsee Keep",
	"Geisternebel Keep",
	"Sturmruine Keep",
	"Trübsalstein Castle",
	"Blutstein Keep"
	"Darkwater Citadel"
	"Phönix Castle",
	"Ehrengarde Bastion",
	"Tugend Castle",
	"Ehren Castle",
	"Castle Schand",
	"Hangman\'s Keep",
	"Castle Finster",
	"Verdammniss Bastion",
	"Drachenflügel Keep"
]);

::Const.World.LocationNames.OrcCamp.extend([
	"Black Crag",
	"Massif Orcal",
	"Gorgoth",
	"The Pit",
	"Bloodmaw Camp",
	"Skullcrush Encampment",
	"Gorehide Camp",
	"Broken Axe Camp",
	"Savage Pike",
	"Bonepile",
	"Doomscar",
	"Redtusk Warcamp",
	"Warlord\'s Maw",
	"Ashfang Pit",
	"Grimhorn Warcamp"
]);

::Const.World.LocationNames.GoblinBase.extend([
	"Eight Peaks",
	"Darkmaw Nest",
	"Dreadclaw Encampment",
	"Blighted Warrens",
	"Blackscar Tangle"
]);

::Const.World.LocationNames.VampireCoven.extend([
	"Castle Drakenhof",
	"Castle Sangfroid"
]);
